/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Desk.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Desk(props) {
  const { nodes, materials } = useGLTF("/models/Desk.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bureau.geometry}
        material={materials.PaletteMaterial001}
        position={[-0.157, 0, -0.198]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Affichage_2.geometry}
        material={materials.html}
        position={[-0.147, 0, -0.097]}
        rotation={[0, 1.039, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.affichage.geometry}
        material={materials.Vscode}
        position={[-0.157, 0, -0.198]}
      />
      <instancedMesh
        castShadow
        receiveShadow
        args={[nodes.Mesh.geometry, materials.PaletteMaterial001, 5]}
        instanceMatrix={nodes.Mesh.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("/models/Desk.glb");
