/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Iles_Export-v3.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Iles(props) {
  const { nodes, materials } = useGLTF('/models/Iles.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ile_haute.geometry} material={materials['Material.004']} position={[1.032, 1.834, -2.6]} rotation={[0, 1.289, 0]} />
      <mesh geometry={nodes.ile_basse.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.riviere.geometry} material={materials.PaletteMaterial001} position={[4.757, -7.809, -8.265]} />
      <instancedMesh args={[nodes.Mesh_2.geometry, materials.PaletteMaterial001, 33]} instanceMatrix={nodes.Mesh_2.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh_3.geometry, materials.PaletteMaterial001, 33]} instanceMatrix={nodes.Mesh_3.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/models/Iles.glb')
